<?php

use Nakshatra\Popup\ViewModel\PopupViewModel as PopupViewModel;
use Magento\Framework\View\Element\Template;

/** @var Template $block*/
/** @var PopupViewModel $viewModel */
$viewModel = $block->getData('view_model');
$popup = $viewModel->getPopup();
?>
<div data-bind="mageInit: {
        'Nakshatra_Popup/js/popup':{
            'timeout': <?= /* @noEscape */ $popup->getTimeout(); ?>,
            'content': '<?= $popup->getContent(); ?>'
        }}">
</div>


