<?php

namespace Nakshatra\Popup\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;
use Magento\Framework\Model\AbstractModel;

class Popup extends AbstractDb
{
    private const TABLE_NAME = 'nakshatra_popup';
    private const FIELD_NAME = 'popup_id';


    protected function _construct()
    {
        $this->_init(self::TABLE_NAME, self::FIELD_NAME);
    }

    protected function _beforeSave(AbstractModel $object)
    {
        $object->setData('updated_at');
        return parent::_beforeSave($object); // TODO: Change the autogenerated stub
    }
}
